### ISSUE TITLE
Failed to install (Eclipse Kepler)

### ISSUE THREAD

**Issue by rtm81** [missedone/navigatorext#1]
I am trying to install the plugin to my eclipse Kepler installation via Eclipse Marketplace, but i get a nasty error.

Cannot complete the install because one or more required items could not be found.
  Software being installed: Eclipse Navigator Extension Feature 1.1.2.201201311435 (com.googlecode.eclipse.navigatorext.features.feature.group 1.1.2.201201311435)
  Missing requirement: Eclipse Navigator Extension 1.1.2.201201311435 (com.googlecode.eclipse.navigatorext 1.1.2.201201311435) requires 'bundle org.junit4 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Eclipse Navigator Extension Feature 1.1.2.201201311435 (com.googlecode.eclipse.navigatorext.features.feature.group 1.1.2.201201311435)
    To: com.googlecode.eclipse.navigatorext [1.1.2.201201311435]

Please see the discussion here (https://github.com/infinitest/infinitest/issues/111). They are addressing the same issue.

**Comment by missedone** [comment]
this was fixed, please use plugin version of [1.1.3](https://github.com/missedone/navigatorext/raw/master/archives/nax_1.1.3.201504230935.zip)
