### ISSUE TITLE
Doesn't work with folders with spaces in them

### ISSUE THREAD

**Issue by VadimKorkin** [missedone/navigatorext#2]
Hi Nick,

I found that if the file path has a space in it the plugin doesn't work with it. ShellContextMenu sees it as 2 parameters instead of one file name. For example
ShellContextMenu.exe 10000 C:\folder 1\folder 2\file2.java
Such issues are resolved by enclosing the file path in parentheses.
ShellContextMenu.exe 10000 "C:\folder 1\folder 2\file2.java"

I downloaded the master from this repo and fixed this in 2 places:
Activator.initializeDefaults:

```
String params = " 10000 \"{0}\"";'
```

ShowContextMenu.showContextMenu:

```
    if (target.indexOf("{0}") == -1) {
                target = target.trim() + " \"{0}\"";
            }
```

Then I compiled it with tycho 0.19 and for the Luna Release. In the main pom:

``` xml
<properties>
        <tycho.version>0.19.0</tycho.version>
    </properties>
<repositories>
        <repository>
            <id>luna</id>
            <layout>p2</layout>
            <url>http://download.eclipse.org/releases/luna</url>
        </repository>
    </repositories>
```

And then installed on my Luna SR1 from the generated local site. Everything worked fine. 
Could you make this useful change available for others? 

And thank you for your effort! It is a very useful plugin, I use it every day to check-in/check-out files from ClearCase. Good work!

**Comment by missedone** [comment]
Hi VadimKorkin
Thanks very much to bring this up and fixed it, i updated the plugin of version [1.1.3](https://github.com/missedone/navigatorext/raw/master/archives/nax_1.1.3.201504230935.zip)
