### ISSUE TITLE
New Release / update site

### ISSUE THREAD

**Issue by AndreasAumayr** [missedone/navigatorext#3]
Hi,

is there any chance that you provide a new release branch (like the 1.1.2) or update-site for this plugin?
I'm currently preparing an eclipse installation for our dev team and I
- cannot use the update site at sourceforge (javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure)
- cannot use the released version (1.1.2) as a local update site (requires 'bundle org.junit4 0.0.0' but it could not be found - see Issue #1 )

Using a local copy of the current master branch as local update site works, but I'd prefer to use any kind of tagged version..

Best Regards,

Andreas

**Comment by missedone** [comment]
hi @AndreasAumayr , i just added the missing tag [v1.1.3](https://github.com/missedone/navigatorext/tree/v1.1.3/site), could you check if that works for you?

**Comment by missedone** [comment]
you can use this update site url: `https://raw.github.com/missedone/navigatorext/v1.1.3/site`

**Comment by AndreasAumayr** [comment]
Wow that was fast - thank you!

I just tried using the update-site you provided.
The installation itself worked, but when launching eclipse (Neon), and selecting "Show Context Menu" there's a usage error:

>Usage: ShellContextMenu <milliseconds> <file | directory> ...

The preferences ("Context Menu > Target") are
> <Path to my workspace>\.metadata\.plugins\com.googlecode.eclipse.navigatorext\ShellContextMenu.exe 10000 {0}

Using the current master locally works (as stated above). The preferences ("Context Menu > Target") are
> <Path to my workspace>\.metadata\.plugins\com.googlecode.eclipse.navigatorext\ShellContextMenu.exe 10000 "{0}"

Seems like there are missing quotes within the (default) preferences of the tag 1.13. If I manually add them, everything works as expected!

Thank you for the fast fix / response - i appreciate this

**Comment by missedone** [comment]
sure, try the new one pls: `https://raw.github.com/missedone/navigatorext/v1.1.3.1/site`

**Comment by AndreasAumayr** [comment]
Works like a charm. Thank you!
